name: "CI"

on: [push, pull_request]

env:
  PROJECT_PATH: 'src/Hrimsoft.Data.PostgreSql/Hrimsoft.Data.PostgreSql.csproj'
  TESTS_PROJECT_PATH: 'tests/Hrimsoft.Data.PostgreSql.Tests/Hrimsoft.Data.PostgreSql.Tests.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: 'Unit tests'
      run: dotnet test ${{ env.TESTS_PROJECT_PATH }}